import type { Metadata } from "next";
import "./globals.css";
import { inter, primary, secondary, tertiary } from "@/lib/font";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${primary.variable} ${secondary.variable} ${tertiary.variable} ${inter.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
